// Generated by Apple Swift version 2.2 (swiftlang-703.0.18.1 clang-703.0.29)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import UIKit;
@import CoreGraphics;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class UICollectionViewCell;
@class UICollectionView;
@class NSIndexPath;
@class NSOperation;
@class FOCollectionSection;
@class UIViewController;

SWIFT_CLASS("_TtC13FOCollections16FOCollectionItem")
@interface FOCollectionItem : NSObject <UIScrollViewDelegate, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout>
@property (nonatomic, strong) id _Nullable data;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSString * _Nullable reuseIdentifier;
@property (nonatomic) Class _Nullable cellClass;
@property (nonatomic) NSInteger columns;
@property (nonatomic, weak) FOCollectionSection * _Nullable section;
@property (nonatomic, weak) UIViewController * _Nullable viewController;
- (void)configure:(UICollectionViewCell * _Nonnull)cell collectionView:(UICollectionView * _Nonnull)collectionView indexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSOperation * _Nullable)getResourceForKey:(NSString * _Nonnull)key collectionView:(UICollectionView * _Nonnull)collectionView indexPath:(NSIndexPath * _Nonnull)indexPath completion:(void (^ _Nonnull)(id _Nullable, id _Nullable))completion;
- (void)setResource:(id _Nullable)resource result:(id _Nullable)result forKey:(NSString * _Nonnull)key collectionView:(UICollectionView * _Nonnull)collectionView indexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSArray<NSString *> * _Nonnull)resourceKeys;
- (NSArray<NSOperation *> * _Nonnull)getResources:(UICollectionView * _Nonnull)collectionView indexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSArray<UICollectionViewCell *> * _Nonnull)cells;
- (BOOL)isEqual:(id _Nullable)o;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FOCollections19FOCollectionSection")
@interface FOCollectionSection : NSObject <UIScrollViewDelegate, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout>
@property (nonatomic, copy) NSArray<FOCollectionItem *> * _Nullable items;
@property (nonatomic, copy) NSString * _Nullable identifier;
- (FOCollectionItem * _Nullable)itemAtIndex:(NSInteger)index;
- (void)pageFetchComplete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class FOCollectionViewDataSource;
@class NSOperationQueue;
@class UITraitCollection;
@protocol UIViewControllerTransitionCoordinator;
@class NSIndexSet;
@class UICollectionViewLayout;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC13FOCollections26FOCollectionViewController")
@interface FOCollectionViewController : UICollectionViewController
@property (nonatomic, readonly, strong) FOCollectionViewDataSource * _Nonnull dataSource;
@property (nonatomic) CGFloat pagingThreshold;
@property (nonatomic, strong) NSOperationQueue * _Nonnull queue;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)willTransitionToTraitCollection:(UITraitCollection * _Nonnull)newCollection withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
- (void)queueUpdate:(void (^ _Nonnull)(void))update completion:(void (^ _Nullable)(BOOL))completion;
- (void)queueWork:(void (^ _Nonnull)(void))work;
- (void)insertSections:(NSArray<FOCollectionSection *> * _Nullable)sections indexes:(NSIndexSet * _Nonnull)indexes;
- (void)deleteSectionsAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)insertItems:(NSArray<FOCollectionItem *> * _Nullable)items indexPaths:(NSArray<NSIndexPath *> * _Nullable)indexPaths;
- (void)deleteItemsAtIndexPaths:(NSArray<NSIndexPath *> * _Nullable)indexPaths;
- (void)appendItems:(NSArray<FOCollectionItem *> * _Nonnull)items toSectionAtIndex:(NSInteger)sectionIndex;
- (void)prependItems:(NSArray<FOCollectionItem *> * _Nonnull)items toSectionAtIndex:(NSInteger)sectionIndex;
- (void)clearAllItems;
- (FOCollectionItem * _Nonnull)pagingItemForSection:(FOCollectionSection * _Nonnull)section;
- (void)refreshVisibleCells;
- (void)nextPageForSection:(FOCollectionSection * _Nonnull)section collectionView:(UICollectionView * _Nonnull)collectionView;
- (void)clearCellSizeCache:(BOOL)keepCapacity;
- (nonnull instancetype)initWithCollectionViewLayout:(UICollectionViewLayout * _Nonnull)layout OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface FOCollectionViewController (SWIFT_EXTENSION(FOCollections)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout referenceSizeForHeaderInSection:(NSInteger)section;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout referenceSizeForFooterInSection:(NSInteger)section;
- (UICollectionViewCell * _Nullable)layoutCellForIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class UICollectionReusableView;

@interface FOCollectionViewController (SWIFT_EXTENSION(FOCollections))
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldHighlightItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didHighlightItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didUnhighlightItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldDeselectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didDeselectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView willDisplayCell:(UICollectionViewCell * _Nonnull)cell forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView willDisplaySupplementaryView:(UICollectionReusableView * _Nonnull)view forElementKind:(NSString * _Nonnull)elementKind atIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didEndDisplayingCell:(UICollectionViewCell * _Nonnull)cell forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didEndDisplayingSupplementaryView:(UICollectionReusableView * _Nonnull)view forElementOfKind:(NSString * _Nonnull)elementKind atIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldShowMenuForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView canPerformAction:(SEL _Null_unspecified)action forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath withSender:(id _Nullable)sender;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView performAction:(SEL _Null_unspecified)action forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath withSender:(id _Nullable)sender;

/// override public func collectionView(collectionView: UICollectionView, transitionLayoutForOldLayout fromLayout: UICollectionViewLayout, newLayout toLayout: UICollectionViewLayout) -> UICollectionViewTransitionLayout { }
///
/// <ul><li></li></ul>
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView canFocusItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC13FOCollections26FOCollectionViewDataSource")
@interface FOCollectionViewDataSource : NSObject
- (void)insertSections:(NSArray<FOCollectionSection *> * _Nullable)sections atIndexes:(NSIndexSet * _Nonnull)indexes collectionView:(UICollectionView * _Nonnull)collectionView viewController:(UIViewController * _Nonnull)viewController;
- (void)deleteSectionsAtIndexes:(NSIndexSet * _Nonnull)indexes collectionView:(UICollectionView * _Nonnull)collectionView;
- (void)insertItems:(NSArray<FOCollectionItem *> * _Nonnull)items atIndexPaths:(NSArray<NSIndexPath *> * _Nonnull)indexPaths collectionView:(UICollectionView * _Nonnull)collectionView viewController:(UIViewController * _Nonnull)viewController;
- (void)deleteItemsAtIndexPaths:(NSArray<NSIndexPath *> * _Nonnull)indexPaths collectionView:(UICollectionView * _Nonnull)collectionView;
- (NSArray<NSIndexPath *> * _Nullable)appendItems:(NSArray<FOCollectionItem *> * _Nonnull)items toSectionAtIndex:(NSInteger)sectionIndex collectionView:(UICollectionView * _Nonnull)collectionView viewController:(UIViewController * _Nonnull)viewController;
- (NSArray<NSIndexPath *> * _Nullable)prependItems:(NSArray<FOCollectionItem *> * _Nonnull)items toSectionAtIndex:(NSInteger)sectionIndex collectionView:(UICollectionView * _Nonnull)collectionView viewController:(UIViewController * _Nonnull)viewController;
- (NSIndexSet * _Nullable)clearAllItems:(UICollectionView * _Nonnull)collectionView;
- (FOCollectionSection * _Nullable)sectionAtIndex:(NSInteger)index;
- (FOCollectionItem * _Nullable)itemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (id _Nullable)dataAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSIndexSet * _Nonnull)indexesForSection:(FOCollectionSection * _Nonnull)section;
- (NSArray<NSIndexPath *> * _Nonnull)indexPathsForItem:(FOCollectionItem * _Nonnull)item;
- (NSArray<NSIndexPath *> * _Nullable)indexPathsForData:(id _Nonnull)data;
- (NSArray<UICollectionViewCell *> * _Nonnull)cellsForItem:(FOCollectionItem * _Nonnull)item collectionView:(UICollectionView * _Nonnull)collectionView;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface FOCollectionViewDataSource (SWIFT_EXTENSION(FOCollections)) <UICollectionViewDataSource>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView;
@end


@interface FOCollectionViewDataSource (SWIFT_EXTENSION(FOCollections))
- (NSIndexPath * _Nullable)indexPathForIndex:(NSInteger)index;
- (NSIndexPath * _Nullable)previousIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSIndexPath * _Nullable)nextIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class UITableViewCell;
@class UITableView;
@class FOTableSection;

SWIFT_CLASS("_TtC13FOCollections11FOTableItem")
@interface FOTableItem : NSObject <UIScrollViewDelegate, UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, strong) id _Nullable data;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSString * _Nullable reuseIdentifier;
@property (nonatomic) Class _Nullable cellClass;
@property (nonatomic, weak) FOTableSection * _Nullable section;
@property (nonatomic, weak) UIViewController * _Nullable viewController;
- (void)configure:(UITableViewCell * _Nonnull)cell tableView:(UITableView * _Nonnull)tableView indexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSOperation * _Nullable)getResourceForKey:(NSString * _Nonnull)key tableView:(UITableView * _Nonnull)tableView indexPath:(NSIndexPath * _Nonnull)indexPath completion:(void (^ _Nonnull)(id _Nullable, id _Nullable))completion;
- (void)setResource:(id _Nullable)resource result:(id _Nullable)result forKey:(NSString * _Nonnull)key tableView:(UITableView * _Nonnull)tableView indexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSArray<NSString *> * _Nonnull)resourceKeys;
- (NSArray<NSOperation *> * _Nonnull)getResources:(UITableView * _Nonnull)tableView indexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSArray<UITableViewCell *> * _Nonnull)cells;
- (BOOL)isEqual:(id _Nullable)o;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FOCollections14FOTableSection")
@interface FOTableSection : NSObject
@property (nonatomic, copy) NSArray<FOTableItem *> * _Nullable items;
@property (nonatomic, copy) NSString * _Nullable identifier;
- (FOTableItem * _Nullable)itemAtIndex:(NSInteger)index;
- (void)pageFetchComplete;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class FOTableViewDataSource;

SWIFT_CLASS("_TtC13FOCollections21FOTableViewController")
@interface FOTableViewController : UIViewController <UIScrollViewDelegate, UITableViewDelegate>
@property (nonatomic, strong) UITableView * _Null_unspecified tableView;
@property (nonatomic, readonly, strong) FOTableViewDataSource * _Nonnull dataSource;
@property (nonatomic) CGFloat pagingThreshold;
@property (nonatomic, strong) NSOperationQueue * _Nonnull queue;
- (nonnull instancetype)initWithFrame:(CGRect)frame style:(UITableViewStyle)style;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)willTransitionToTraitCollection:(UITraitCollection * _Nonnull)newCollection withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
- (void)queueUpdate:(void (^ _Nonnull)(void))update completion:(void (^ _Nullable)(void))completion;
- (void)queueWork:(void (^ _Nonnull)(void))work;
- (void)insertSections:(NSArray<FOTableSection *> * _Nonnull)sections indexes:(NSIndexSet * _Nonnull)indexes animation:(UITableViewRowAnimation)animation;
- (void)deleteSectionsAtIndexes:(NSIndexSet * _Nonnull)indexes animation:(UITableViewRowAnimation)animation;
- (void)insertItems:(NSArray<FOTableItem *> * _Nonnull)items indexPaths:(NSArray<NSIndexPath *> * _Nonnull)indexPaths animation:(UITableViewRowAnimation)animation;
- (void)deleteItemsAtIndexPaths:(NSArray<NSIndexPath *> * _Nonnull)indexPaths animation:(UITableViewRowAnimation)animation;
- (void)appendItems:(NSArray<FOTableItem *> * _Nonnull)items toSectionAtIndex:(NSInteger)sectionIndex animation:(UITableViewRowAnimation)animation;
- (void)prependItems:(NSArray<FOTableItem *> * _Nonnull)items toSectionAtIndex:(NSInteger)sectionIndex animation:(UITableViewRowAnimation)animation fixedOffset:(BOOL)fixedOffset;
- (void)clearAllItems:(UITableViewRowAnimation)animation;
- (FOTableItem * _Nonnull)pagingItemForSection:(FOTableSection * _Nonnull)section;
- (void)refreshVisibleCells;
- (void)nextPageForSection:(FOTableSection * _Nonnull)section tableView:(UITableView * _Nonnull)tableView;
- (void)clearCellSizeCache:(BOOL)keepCapacity;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIView;
@class UITableViewRowAction;

@interface FOTableViewController (SWIFT_EXTENSION(FOCollections))
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayCell:(UITableViewCell * _Nonnull)cell forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayHeaderView:(UIView * _Nonnull)view forSection:(NSInteger)section;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayFooterView:(UIView * _Nonnull)view forSection:(NSInteger)section;
- (void)tableView:(UITableView * _Nonnull)tableView didEndDisplayingCell:(UITableViewCell * _Nonnull)cell forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didEndDisplayingHeaderView:(UIView * _Nonnull)view forSection:(NSInteger)section;
- (void)tableView:(UITableView * _Nonnull)tableView didEndDisplayingFooterView:(UIView * _Nonnull)view forSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView estimatedHeightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView estimatedHeightForHeaderInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView estimatedHeightForFooterInSection:(NSInteger)section;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForFooterInSection:(NSInteger)section;
- (void)tableView:(UITableView * _Nonnull)tableView accessoryButtonTappedForRowWithIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)tableView:(UITableView * _Nonnull)tableView shouldHighlightRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didHighlightRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didUnhighlightRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSIndexPath * _Nullable)tableView:(UITableView * _Nonnull)tableView willSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSIndexPath * _Nullable)tableView:(UITableView * _Nonnull)tableView willDeselectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didDeselectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (UITableViewCellEditingStyle)tableView:(UITableView * _Nonnull)tableView editingStyleForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSString * _Nullable)tableView:(UITableView * _Nonnull)tableView titleForDeleteConfirmationButtonForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSArray<UITableViewRowAction *> * _Nullable)tableView:(UITableView * _Nonnull)tableView editActionsForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)tableView:(UITableView * _Nonnull)tableView shouldIndentWhileEditingRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView willBeginEditingRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didEndEditingRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;

/// override public func tableView(tableView: UITableView, targetIndexPathForMoveFromRowAtIndexPath sourceIndexPath: NSIndexPath, toProposedIndexPath proposedDestinationIndexPath: NSIndexPath) -> NSIndexPath { }
///
/// <ul><li></li></ul>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView indentationLevelForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)tableView:(UITableView * _Nonnull)tableView shouldShowMenuForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)tableView:(UITableView * _Nonnull)tableView canPerformAction:(SEL _Null_unspecified)action forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath withSender:(id _Nullable)sender;
- (void)tableView:(UITableView * _Nonnull)tableView performAction:(SEL _Null_unspecified)action forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath withSender:(id _Nullable)sender;
- (BOOL)tableView:(UITableView * _Nonnull)tableView canFocusRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (UITableViewCell * _Nullable)layoutCellForIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC13FOCollections21FOTableViewDataSource")
@interface FOTableViewDataSource : NSObject
- (void)insertSections:(NSArray<FOTableSection *> * _Nonnull)sections atIndexes:(NSIndexSet * _Nonnull)indexes tableView:(UITableView * _Nonnull)tableView viewController:(UIViewController * _Nonnull)viewController;
- (void)deleteSectionsAtIndexes:(NSIndexSet * _Nonnull)indexes tableView:(UITableView * _Nonnull)tableView;
- (void)insertItems:(NSArray<FOTableItem *> * _Nonnull)items atIndexPaths:(NSArray<NSIndexPath *> * _Nonnull)indexPaths tableView:(UITableView * _Nonnull)tableView viewController:(UIViewController * _Nonnull)viewController;
- (void)deleteItemsAtIndexPaths:(NSArray<NSIndexPath *> * _Nonnull)indexPaths tableView:(UITableView * _Nonnull)tableView;
- (NSArray<NSIndexPath *> * _Nullable)appendItems:(NSArray<FOTableItem *> * _Nonnull)items toSectionAtIndex:(NSInteger)sectionIndex tableView:(UITableView * _Nonnull)tableView viewController:(UIViewController * _Nonnull)viewController;
- (NSArray<NSIndexPath *> * _Nullable)prependItems:(NSArray<FOTableItem *> * _Nonnull)items toSectionAtIndex:(NSInteger)sectionIndex tableView:(UITableView * _Nonnull)tableView viewController:(UIViewController * _Nonnull)viewController;
- (NSIndexSet * _Nullable)clearAllItems:(UITableView * _Nonnull)tableView;
- (FOTableSection * _Nullable)sectionAtIndex:(NSInteger)index;
- (FOTableItem * _Nullable)itemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (id _Nullable)dataAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSIndexSet * _Nonnull)indexesForSection:(FOTableSection * _Nonnull)section;
- (NSArray<NSIndexPath *> * _Nonnull)indexPathsForItem:(FOTableItem * _Nonnull)item;
- (NSArray<NSIndexPath *> * _Nullable)indexPathsForData:(id _Nonnull)data;
- (NSArray<UITableViewCell *> * _Nonnull)cellsForItem:(FOTableItem * _Nonnull)item tableView:(UITableView * _Nonnull)tableView;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface FOTableViewDataSource (SWIFT_EXTENSION(FOCollections))
- (FOTableItem * _Nullable)itemAtIndex:(NSInteger)index;
- (NSIndexPath * _Nullable)indexPathForIndex:(NSInteger)index;
- (NSIndexPath * _Nullable)previousIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSIndexPath * _Nullable)nextIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface FOTableViewDataSource (SWIFT_EXTENSION(FOCollections)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (NSString * _Nullable)tableView:(UITableView * _Nonnull)tableView titleForHeaderInSection:(NSInteger)section;
- (NSString * _Nullable)tableView:(UITableView * _Nonnull)tableView titleForFooterInSection:(NSInteger)section;
- (BOOL)tableView:(UITableView * _Nonnull)tableView canEditRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)tableView:(UITableView * _Nonnull)tableView canMoveRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;

/// func sectionIndexTitlesForTableView(tableView: UITableView) -> [String]? { }
///
/// func tableView(tableView: UITableView, sectionForSectionIndexTitle title: String, atIndex index: Int) -> Int {
/// }
///
/// <ul><li></li></ul>
- (void)tableView:(UITableView * _Nonnull)tableView commitEditingStyle:(UITableViewCellEditingStyle)editingStyle forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface NSIndexPath (SWIFT_EXTENSION(FOCollections))
@end

#pragma clang diagnostic pop
