// Generated by Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import UIKit;
@import CoreGraphics;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class UICollectionViewCell;
@class UICollectionView;
@class NSIndexPath;
@class NSOperation;
@class FOCollectionSection;
@class UIViewController;

SWIFT_CLASS("_TtC13FOCollections16FOCollectionItem")
@interface FOCollectionItem : NSObject <UIScrollViewDelegate, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout>
@property (nonatomic, strong) id __nullable data;
@property (nonatomic, copy) NSString * __nullable identifier;
@property (nonatomic, copy) NSString * __nullable reuseIdentifier;
@property (nonatomic) Class __nullable cellClass;
@property (nonatomic) NSInteger columns;
@property (nonatomic, weak) FOCollectionSection * __nullable section;
@property (nonatomic, weak) UIViewController * __nullable viewController;
- (void)configure:(UICollectionViewCell * __nonnull)cell collectionView:(UICollectionView * __nonnull)collectionView indexPath:(NSIndexPath * __nonnull)indexPath;
- (NSOperation * __nullable)getResourceForKey:(NSString * __nonnull)key collectionView:(UICollectionView * __nonnull)collectionView indexPath:(NSIndexPath * __nonnull)indexPath completion:(void (^ __nonnull)(id __nonnull, id __nonnull))completion;
- (void)setResource:(id __nonnull)resource result:(id __nonnull)result forKey:(NSString * __nonnull)key collectionView:(UICollectionView * __nonnull)collectionView indexPath:(NSIndexPath * __nonnull)indexPath;
- (NSArray<NSString *> * __nonnull)resourceKeys;
- (NSArray<NSOperation *> * __nonnull)getResources:(UICollectionView * __nonnull)collectionView indexPath:(NSIndexPath * __nonnull)indexPath;
- (BOOL)isEqual:(id __nullable)o;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FOCollections19FOCollectionSection")
@interface FOCollectionSection : NSObject <UIScrollViewDelegate, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout>
@property (nonatomic, copy) NSArray<FOCollectionItem *> * __nullable items;
@property (nonatomic, copy) NSString * __nullable identifier;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class FOCollectionViewDataSource;
@class UITraitCollection;
@protocol UIViewControllerTransitionCoordinator;
@class NSIndexSet;
@class UICollectionViewLayout;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC13FOCollections26FOCollectionViewController")
@interface FOCollectionViewController : UICollectionViewController
@property (nonatomic, readonly, strong) FOCollectionViewDataSource * __nonnull dataSource;
@property (nonatomic) CGFloat pagingThreshold;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)willTransitionToTraitCollection:(UITraitCollection * __nonnull)newCollection withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> __nonnull)coordinator;
- (void)queueUpdate:(void (^ __nonnull)(void))update completion:(void (^ __nullable)(BOOL))completion;
- (void)insertSections:(NSArray<FOCollectionSection *> * __nullable)sections indexes:(NSIndexSet * __nonnull)indexes;
- (void)deleteSectionsAtIndexes:(NSIndexSet * __nonnull)indexes;
- (void)insertItems:(NSArray<FOCollectionItem *> * __nullable)items indexPaths:(NSArray<NSIndexPath *> * __nullable)indexPaths;
- (void)deleteItemsAtIndexPaths:(NSArray<NSIndexPath *> * __nullable)indexPaths;
- (void)appendItems:(NSArray<FOCollectionItem *> * __nonnull)items toSectionAtIndex:(NSInteger)sectionIndex;
- (void)clearAllItems;
- (void)nextPageForSection:(NSInteger)section collectionView:(UICollectionView * __nonnull)collectionView;
- (nonnull instancetype)initWithCollectionViewLayout:(UICollectionViewLayout * __nonnull)layout OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface FOCollectionViewController (SWIFT_EXTENSION(FOCollections)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * __nonnull)collectionView layout:(UICollectionViewLayout * __nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (UIEdgeInsets)collectionView:(UICollectionView * __nonnull)collectionView layout:(UICollectionViewLayout * __nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section;
- (CGFloat)collectionView:(UICollectionView * __nonnull)collectionView layout:(UICollectionViewLayout * __nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section;
- (CGFloat)collectionView:(UICollectionView * __nonnull)collectionView layout:(UICollectionViewLayout * __nonnull)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section;
- (CGSize)collectionView:(UICollectionView * __nonnull)collectionView layout:(UICollectionViewLayout * __nonnull)collectionViewLayout referenceSizeForHeaderInSection:(NSInteger)section;
- (CGSize)collectionView:(UICollectionView * __nonnull)collectionView layout:(UICollectionViewLayout * __nonnull)collectionViewLayout referenceSizeForFooterInSection:(NSInteger)section;
- (UICollectionViewCell * __nullable)layoutCellForIndexPath:(NSIndexPath * __nonnull)indexPath;
@end

@class UICollectionReusableView;

@interface FOCollectionViewController (SWIFT_EXTENSION(FOCollections))
- (BOOL)collectionView:(UICollectionView * __nonnull)collectionView shouldHighlightItemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)collectionView:(UICollectionView * __nonnull)collectionView didHighlightItemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)collectionView:(UICollectionView * __nonnull)collectionView didUnhighlightItemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (BOOL)collectionView:(UICollectionView * __nonnull)collectionView shouldSelectItemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (BOOL)collectionView:(UICollectionView * __nonnull)collectionView shouldDeselectItemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)collectionView:(UICollectionView * __nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)collectionView:(UICollectionView * __nonnull)collectionView didDeselectItemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)collectionView:(UICollectionView * __nonnull)collectionView willDisplayCell:(UICollectionViewCell * __nonnull)cell forItemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)collectionView:(UICollectionView * __nonnull)collectionView willDisplaySupplementaryView:(UICollectionReusableView * __nonnull)view forElementKind:(NSString * __nonnull)elementKind atIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)collectionView:(UICollectionView * __nonnull)collectionView didEndDisplayingCell:(UICollectionViewCell * __nonnull)cell forItemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)collectionView:(UICollectionView * __nonnull)collectionView didEndDisplayingSupplementaryView:(UICollectionReusableView * __nonnull)view forElementOfKind:(NSString * __nonnull)elementKind atIndexPath:(NSIndexPath * __nonnull)indexPath;
- (BOOL)collectionView:(UICollectionView * __nonnull)collectionView shouldShowMenuForItemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (BOOL)collectionView:(UICollectionView * __nonnull)collectionView canPerformAction:(SEL __null_unspecified)action forItemAtIndexPath:(NSIndexPath * __nonnull)indexPath withSender:(id __nullable)sender;
- (void)collectionView:(UICollectionView * __nonnull)collectionView performAction:(SEL __null_unspecified)action forItemAtIndexPath:(NSIndexPath * __nonnull)indexPath withSender:(id __nullable)sender;

/// override public func collectionView(collectionView: UICollectionView, transitionLayoutForOldLayout fromLayout: UICollectionViewLayout, newLayout toLayout: UICollectionViewLayout) -> UICollectionViewTransitionLayout { }
///
/// <ul><li></li></ul>
- (BOOL)collectionView:(UICollectionView * __nonnull)collectionView canFocusItemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
@end


SWIFT_CLASS("_TtC13FOCollections26FOCollectionViewDataSource")
@interface FOCollectionViewDataSource : NSObject
- (void)insertSections:(NSArray<FOCollectionSection *> * __nullable)sections atIndexes:(NSIndexSet * __nonnull)indexes collectionView:(UICollectionView * __nonnull)collectionView viewController:(UIViewController * __nonnull)viewController;
- (void)deleteSectionsAtIndexes:(NSIndexSet * __nonnull)indexes collectionView:(UICollectionView * __nonnull)collectionView;
- (void)insertItems:(NSArray<FOCollectionItem *> * __nonnull)items atIndexPaths:(NSArray<NSIndexPath *> * __nonnull)indexPaths collectionView:(UICollectionView * __nonnull)collectionView viewController:(UIViewController * __nonnull)viewController;
- (void)deleteItemsAtIndexPaths:(NSArray<NSIndexPath *> * __nonnull)indexPaths collectionView:(UICollectionView * __nonnull)collectionView;
- (FOCollectionItem * __nonnull)pagingItemForSection:(FOCollectionSection * __nonnull)section;
- (FOCollectionSection * __nullable)sectionAtIndex:(NSInteger)index;
- (FOCollectionItem * __nullable)itemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (id __nullable)dataAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (NSIndexSet * __nonnull)indexesForSection:(FOCollectionSection * __nonnull)section;
- (NSArray<NSIndexPath *> * __nonnull)indexPathsForItem:(FOCollectionItem * __nonnull)item;
- (NSArray<NSIndexPath *> * __nullable)indexPathsForData:(id __nonnull)data;
- (NSArray<UICollectionViewCell *> * __nonnull)cellsForItem:(FOCollectionItem * __nonnull)item collectionView:(UICollectionView * __nonnull)collectionView;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface FOCollectionViewDataSource (SWIFT_EXTENSION(FOCollections)) <UICollectionViewDataSource>
- (NSInteger)collectionView:(UICollectionView * __nonnull)collectionView numberOfItemsInSection:(NSInteger)section;
- (UICollectionViewCell * __nonnull)collectionView:(UICollectionView * __nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * __nonnull)collectionView;
@end


@interface FOCollectionViewDataSource (SWIFT_EXTENSION(FOCollections))
- (NSIndexPath * __nullable)indexPathForIndex:(NSInteger)index;
- (NSIndexPath * __nullable)previousIndexPath:(NSIndexPath * __nonnull)indexPath;
- (NSIndexPath * __nullable)nextIndexPath:(NSIndexPath * __nonnull)indexPath;
@end

@class UITableViewCell;
@class UITableView;
@class FOTableSection;

SWIFT_CLASS("_TtC13FOCollections11FOTableItem")
@interface FOTableItem : NSObject <UIScrollViewDelegate, UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, strong) id __nullable data;
@property (nonatomic, copy) NSString * __nullable identifier;
@property (nonatomic, copy) NSString * __nullable reuseIdentifier;
@property (nonatomic) Class __nullable cellClass;
@property (nonatomic, weak) FOTableSection * __nullable section;
@property (nonatomic, weak) UIViewController * __nullable viewController;
- (void)configure:(UITableViewCell * __nonnull)cell tableView:(UITableView * __nonnull)tableView indexPath:(NSIndexPath * __nonnull)indexPath;
- (NSOperation * __nullable)getResourceForKey:(NSString * __nonnull)key tableView:(UITableView * __nonnull)tableView indexPath:(NSIndexPath * __nonnull)indexPath completion:(void (^ __nonnull)(id __nonnull, id __nonnull))completion;
- (void)setResource:(id __nonnull)resource result:(id __nonnull)result forKey:(NSString * __nonnull)key tableView:(UITableView * __nonnull)tableView indexPath:(NSIndexPath * __nonnull)indexPath;
- (NSArray<NSString *> * __nonnull)resourceKeys;
- (NSArray<NSOperation *> * __nonnull)getResources:(UITableView * __nonnull)tableView indexPath:(NSIndexPath * __nonnull)indexPath;
- (BOOL)isEqual:(id __nullable)o;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13FOCollections14FOTableSection")
@interface FOTableSection : NSObject
@property (nonatomic, copy) NSArray<FOTableItem *> * __nullable items;
@property (nonatomic, copy) NSString * __nullable identifier;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class FOTableViewDataSource;

SWIFT_CLASS("_TtC13FOCollections21FOTableViewController")
@interface FOTableViewController : UITableViewController
@property (nonatomic, readonly, strong) FOTableViewDataSource * __nonnull dataSource;
@property (nonatomic) CGFloat pagingThreshold;
@property (nonatomic) NSTimeInterval updateDuration;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)willTransitionToTraitCollection:(UITraitCollection * __nonnull)newCollection withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> __nonnull)coordinator;
- (void)queueUpdate:(void (^ __nonnull)(void))update completion:(void (^ __nullable)(void))completion;
- (void)insertSections:(NSArray<FOTableSection *> * __nonnull)sections indexes:(NSIndexSet * __nonnull)indexes;
- (void)deleteSectionsAtIndexes:(NSIndexSet * __nonnull)indexes;
- (void)insertItems:(NSArray<FOTableItem *> * __nonnull)items indexPaths:(NSArray<NSIndexPath *> * __nonnull)indexPaths;
- (void)deleteItemsAtIndexPaths:(NSArray<NSIndexPath *> * __nonnull)indexPaths;
- (void)appendItems:(NSArray<FOTableItem *> * __nonnull)items toSectionAtIndex:(NSInteger)sectionIndex;
- (void)clearAllItems;
- (void)nextPageForSection:(NSInteger)section tableView:(UITableView * __nonnull)tableView;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIView;
@class UITableViewRowAction;

@interface FOTableViewController (SWIFT_EXTENSION(FOCollections))
- (void)tableView:(UITableView * __nonnull)tableView willDisplayCell:(UITableViewCell * __nonnull)cell forRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView willDisplayHeaderView:(UIView * __nonnull)view forSection:(NSInteger)section;
- (void)tableView:(UITableView * __nonnull)tableView willDisplayFooterView:(UIView * __nonnull)view forSection:(NSInteger)section;
- (void)tableView:(UITableView * __nonnull)tableView didEndDisplayingCell:(UITableViewCell * __nonnull)cell forRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView didEndDisplayingHeaderView:(UIView * __nonnull)view forSection:(NSInteger)section;
- (void)tableView:(UITableView * __nonnull)tableView didEndDisplayingFooterView:(UIView * __nonnull)view forSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForHeaderInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForFooterInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView * __nonnull)tableView estimatedHeightForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (CGFloat)tableView:(UITableView * __nonnull)tableView estimatedHeightForHeaderInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView * __nonnull)tableView estimatedHeightForFooterInSection:(NSInteger)section;
- (UIView * __nullable)tableView:(UITableView * __nonnull)tableView viewForHeaderInSection:(NSInteger)section;
- (UIView * __nullable)tableView:(UITableView * __nonnull)tableView viewForFooterInSection:(NSInteger)section;
- (void)tableView:(UITableView * __nonnull)tableView accessoryButtonTappedForRowWithIndexPath:(NSIndexPath * __nonnull)indexPath;
- (BOOL)tableView:(UITableView * __nonnull)tableView shouldHighlightRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView didHighlightRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView didUnhighlightRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (NSIndexPath * __nullable)tableView:(UITableView * __nonnull)tableView willSelectRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (NSIndexPath * __nullable)tableView:(UITableView * __nonnull)tableView willDeselectRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView didDeselectRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (UITableViewCellEditingStyle)tableView:(UITableView * __nonnull)tableView editingStyleForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (NSString * __nullable)tableView:(UITableView * __nonnull)tableView titleForDeleteConfirmationButtonForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (NSArray<UITableViewRowAction *> * __nullable)tableView:(UITableView * __nonnull)tableView editActionsForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (BOOL)tableView:(UITableView * __nonnull)tableView shouldIndentWhileEditingRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView willBeginEditingRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView didEndEditingRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;

/// override public func tableView(tableView: UITableView, targetIndexPathForMoveFromRowAtIndexPath sourceIndexPath: NSIndexPath, toProposedIndexPath proposedDestinationIndexPath: NSIndexPath) -> NSIndexPath { }
///
/// <ul><li></li></ul>
- (NSInteger)tableView:(UITableView * __nonnull)tableView indentationLevelForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (BOOL)tableView:(UITableView * __nonnull)tableView shouldShowMenuForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (BOOL)tableView:(UITableView * __nonnull)tableView canPerformAction:(SEL __null_unspecified)action forRowAtIndexPath:(NSIndexPath * __nonnull)indexPath withSender:(id __nullable)sender;
- (void)tableView:(UITableView * __nonnull)tableView performAction:(SEL __null_unspecified)action forRowAtIndexPath:(NSIndexPath * __nonnull)indexPath withSender:(id __nullable)sender;
- (BOOL)tableView:(UITableView * __nonnull)tableView canFocusRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (UITableViewCell * __nullable)layoutCellForIndexPath:(NSIndexPath * __nonnull)indexPath;
@end


SWIFT_CLASS("_TtC13FOCollections21FOTableViewDataSource")
@interface FOTableViewDataSource : NSObject
- (void)insertSections:(NSArray<FOTableSection *> * __nonnull)sections atIndexes:(NSIndexSet * __nonnull)indexes tableView:(UITableView * __nonnull)tableView viewController:(UIViewController * __nonnull)viewController;
- (void)deleteSectionsAtIndexes:(NSIndexSet * __nonnull)indexes tableView:(UITableView * __nonnull)tableView;
- (void)insertItems:(NSArray<FOTableItem *> * __nonnull)items atIndexPaths:(NSArray<NSIndexPath *> * __nonnull)indexPaths tableView:(UITableView * __nonnull)tableView viewController:(UIViewController * __nonnull)viewController;
- (void)deleteItemsAtIndexPaths:(NSArray<NSIndexPath *> * __nonnull)indexPaths tableView:(UITableView * __nonnull)tableView;
- (FOTableItem * __nonnull)pagingItemForSection:(FOTableSection * __nonnull)section;
- (FOTableSection * __nullable)sectionAtIndex:(NSInteger)index;
- (FOTableItem * __nullable)itemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (id __nullable)dataAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (NSIndexSet * __nonnull)indexesForSection:(FOTableSection * __nonnull)section;
- (NSArray<NSIndexPath *> * __nonnull)indexPathsForItem:(FOTableItem * __nonnull)item;
- (NSArray<NSIndexPath *> * __nullable)indexPathsForData:(id __nonnull)data;
- (NSArray<UITableViewCell *> * __nonnull)cellsForItem:(FOTableItem * __nonnull)item tableView:(UITableView * __nonnull)tableView;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface FOTableViewDataSource (SWIFT_EXTENSION(FOCollections))
- (FOTableItem * __nullable)itemAtIndex:(NSInteger)index;
- (NSIndexPath * __nullable)indexPathForIndex:(NSInteger)index;
- (NSIndexPath * __nullable)previousIndexPath:(NSIndexPath * __nonnull)indexPath;
- (NSIndexPath * __nullable)nextIndexPath:(NSIndexPath * __nonnull)indexPath;
@end


@interface FOTableViewDataSource (SWIFT_EXTENSION(FOCollections)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (NSInteger)numberOfSectionsInTableView:(UITableView * __nonnull)tableView;
- (NSString * __nullable)tableView:(UITableView * __nonnull)tableView titleForHeaderInSection:(NSInteger)section;
- (NSString * __nullable)tableView:(UITableView * __nonnull)tableView titleForFooterInSection:(NSInteger)section;
- (BOOL)tableView:(UITableView * __nonnull)tableView canEditRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (BOOL)tableView:(UITableView * __nonnull)tableView canMoveRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;

/// func sectionIndexTitlesForTableView(tableView: UITableView) -> [String]? { }
///
/// func tableView(tableView: UITableView, sectionForSectionIndexTitle title: String, atIndex index: Int) -> Int {
/// }
///
/// <ul><li></li></ul>
- (void)tableView:(UITableView * __nonnull)tableView commitEditingStyle:(UITableViewCellEditingStyle)editingStyle forRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
@end


@interface NSIndexPath (SWIFT_EXTENSION(FOCollections))
@end

#pragma clang diagnostic pop
